/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCTIME_H_RPCGEN
#define _RPCTIME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define RPCTIME 2000001
#define RPCTIMEVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETTIME 1
extern  long * gettime_1(void *, CLIENT *);
extern  long * gettime_1_svc(void *, struct svc_req *);
extern int rpctime_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETTIME 1
extern  long * gettime_1();
extern  long * gettime_1_svc();
extern int rpctime_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCTIME_H_RPCGEN */
